### ISSUE TITLE
Настройка линтеров и форматтеров кода

### ISSUE THREAD

**Issue by eagurin** [eagurin/myaiserv#7]
# Задача: Настройка линтеров и форматтеров кода

## Описание

Необходимо настроить и интегрировать инструменты для автоматического форматирования и проверки качества кода в проекте MCP Server. Это обеспечит единый стиль кодирования, поможет избежать типичных ошибок и улучшит качество кода.

## Инструменты

- [ ] **black**
  - [ ] Установить версию 24.2.0
  - [ ] Настроить максимальную длину строки 88 символов
  - [ ] Добавить конфигурацию в pyproject.toml
  - [ ] Интегрировать с pre-commit хуками

- [ ] **isort**
  - [ ] Установить версию 5.13.2
  - [ ] Настроить профиль совместимый с black
  - [ ] Настроить группировку импортов
  - [ ] Добавить конфигурацию в pyproject.toml
  - [ ] Интегрировать с pre-commit хуками

- [ ] **flake8**
  - [ ] Установить версию 7.0.0
  - [ ] Настроить игнорируемые ошибки
  - [ ] Добавить плагины:
    - [ ] flake8-bugbear
    - [ ] flake8-comprehensions
    - [ ] flake8-docstrings
  - [ ] Создать .flake8 конфигурацию
  - [ ] Интегрировать с pre-commit хуками

- [ ] **mypy**
  - [ ] Установить версию 1.8.0
  - [ ] Настроить строгий режим проверки типов
  - [ ] Добавить конфигурацию в pyproject.toml
  - [ ] Настроить игнорирование определенных ошибок
  - [ ] Интегрировать с pre-commit хуками

- [ ] **ruff**
  - [ ] Установить версию 0.3.0
  - [ ] Настроить правила линтинга
  - [ ] Включить автоматическое исправление
  - [ ] Добавить конфигурацию в pyproject.toml
  - [ ] Интегрировать с pre-commit хуками

## Конфигурация pyproject.toml

```toml
[tool.black]
line-length = 88
target-version = ["py312"]
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/docs/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
split_on_trailing_comma = true
combine_as_imports = true

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[tool.ruff]
line-length = 88
target-version = "py312"
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
]
ignore = []

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**/*" = ["S101"]

[tool.ruff.isort]
known-first-party = ["app"]
```

## Конфигурация .flake8

```ini
[flake8]
max-line-length = 88
extend-ignore = E203, W503
max-complexity = 10
exclude = .git,__pycache__,build,dist,*.egg-info
per-file-ignores =
    __init__.py:F401
    tests/*:S101
```

## Конфигурация pre-commit

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-bugbear
        -   flake8-comprehensions
        -   flake8-docstrings

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies:
        -   types-all

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
```

## Критерии приемки

1. Все инструменты установлены и настроены
2. Конфигурационные файлы созданы и содержат необходимые настройки
3. Pre-commit хуки работают и проверяют код при коммитах
4. Все инструменты успешно работают через команды just
5. Документация по использованию инструментов добавлена в README.md

## Приоритет

Высокий

## Оценка трудозатрат

4 часа

## Связанные файлы

- pyproject.toml
- .flake8
- .pre-commit-config.yaml
- justfile
- README.md

## Дополнительная информация

После настройки всех инструментов необходимо:
1. Запустить форматирование на всей кодовой базе
2. Исправить все найденные ошибки
3. Обновить CI/CD пайплайны для использования этих инструментов
4. Обучить команду использованию новых инструментов
